version: "3.8"

services:
  mysql:
    container_name: users-mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:    
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - ./bookstore-users-api/db/sql/:/docker-entrypoint-initdb.d
      - ./bookstore-users-api/db/data/:/var/lib/mysql
  
  cassandra:
    container_name: oauth-cassandra
    image: cassandra:3.11.11
    restart: always
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"    
    ports:
      - "9042:9042"
    volumes:
      - ./bookstore-oauth-api/db/data/:/var/lib/cassandra
  
  cassandra-load-keyspace:
    container_name: oauth-cassandra-load-keyspace
    image: cassandra:3.11.11
    depends_on:
      - cassandra
    volumes:
      - ./bookstore-oauth-api/db/cql/schema.cql:/schema.cql
    command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s