version: "3.8"

services:
  db:
    container_name: mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:    
      MYSQL_DATABASE: 'users_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - ./bookstore-users-api/db/sql/:/docker-entrypoint-initdb.d